"""Analysis Planning and Execution Layer with Extensible Analysis Registry."""
from app.services.analysis.models import (
    AnalysisPlan,
    AnalysisTask,
    DataRetrievalRequirement,
    AnalysisTaskResult,
    AnalysisExecutionResult,
    AnalysisResult,
    ComputationType,
    InvestigationMode,
    QueryTaskStatus,
    QueryExecutionStatus,
    EvidenceType,
    InvestigationStatus,
    QueryTask,
    QueryExecutionRecord,
    EvidenceItem,
    HypothesisStatus,
    Hypothesis,
    ValidationIssueType,
    ValidationSeverity,
    ValidationIssueStatus,
    ValidationIssue,
    InvestigationPlan,
    InvestigationState,
    PlanningValidationError,
    validate_investigation_plan,
)
from app.services.analysis.investigation_engine import InvestigationEngine
from app.services.analysis.evidence_manager import (
    EvidenceManager,
    InvestigationProgressEvaluator,
    InvestigationProgress,
)
from app.services.analysis.query_selector import (
    QuerySelector,
    QuerySelectorConfig,
    QuerySelectionResult,
    CandidateEvaluation,
)
from app.services.analysis.hypothesis_manager import (
    HypothesisManager,
    SegmentContribution,
)
from app.services.analysis.cross_query_validator import (
    CrossQueryValidator,
    ValidationReport,
    GroundingReadiness,
)
from app.services.analysis.grounded_report_composer import (
    GroundedAnalysisContext,
    GroundedReportComposer,
)
from app.services.analysis.production_optimizer import (
    ModelRouter,
    ModelTier,
    ModelRouteDecision,
    QueryDeduplicator,
    InvestigationCache,
    SemanticQueryCache,
    SelfConsistencyGate,
    SystemMetricsTracker,
    TelemetrySnapshot,
    investigation_cache,
    semantic_query_cache,
)
from app.services.analysis.registry import ANALYSIS_REGISTRY, AnalysisStrategyRegistry
from app.services.analysis.planner import AnalysisPlanner
from app.services.analysis.executor import AnalysisExecutor
from app.services.analysis.analyzers import (
    BaseAnalysisAnalyzer,
    AggregationAnalyzer,
    ComparisonAnalyzer,
    TrendAnalyzer,
    DistributionAnalyzer,
    CorrelationAnalyzer,
    AnomalyAnalyzer,
    SegmentationAnalyzer,
    RootCauseAnalyzer,
    ForecastingAnalyzer,
    StatisticalTestAnalyzer,
    DataQualityAnalyzer,
    ExploratoryAnalyzer,
)

__all__ = [
    "AnalysisPlan",
    "AnalysisTask",
    "DataRetrievalRequirement",
    "AnalysisTaskResult",
    "AnalysisExecutionResult",
    "AnalysisResult",
    "ComputationType",
    "InvestigationMode",
    "QueryTaskStatus",
    "QueryExecutionStatus",
    "EvidenceType",
    "InvestigationStatus",
    "QueryTask",
    "QueryExecutionRecord",
    "EvidenceItem",
    "HypothesisStatus",
    "Hypothesis",
    "InvestigationPlan",
    "InvestigationState",
    "InvestigationEngine",
    "EvidenceManager",
    "InvestigationProgressEvaluator",
    "InvestigationProgress",
    "QuerySelector",
    "QuerySelectorConfig",
    "QuerySelectionResult",
    "CandidateEvaluation",
    "HypothesisManager",
    "SegmentContribution",
    "ValidationIssueType",
    "ValidationSeverity",
    "ValidationIssueStatus",
    "ValidationIssue",
    "CrossQueryValidator",
    "ValidationReport",
    "GroundingReadiness",
    "GroundedAnalysisContext",
    "GroundedReportComposer",
    "ModelRouter",
    "ModelTier",
    "ModelRouteDecision",
    "QueryDeduplicator",
    "InvestigationCache",
    "SemanticQueryCache",
    "SelfConsistencyGate",
    "SystemMetricsTracker",
    "TelemetrySnapshot",
    "investigation_cache",
    "semantic_query_cache",
    "PlanningValidationError",
    "validate_investigation_plan",
    "ANALYSIS_REGISTRY",
    "AnalysisStrategyRegistry",
    "AnalysisPlanner",
    "AnalysisExecutor",
    "BaseAnalysisAnalyzer",
    "AggregationAnalyzer",
    "ComparisonAnalyzer",
    "TrendAnalyzer",
    "DistributionAnalyzer",
    "CorrelationAnalyzer",
    "AnomalyAnalyzer",
    "SegmentationAnalyzer",
    "RootCauseAnalyzer",
    "ForecastingAnalyzer",
    "StatisticalTestAnalyzer",
    "DataQualityAnalyzer",
    "ExploratoryAnalyzer",
]
